name: master

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: es-with-sudachi
  ELASTIC_VER: 7.10.2
  SUDACHI_PLUGIN_VER: 3.1.0

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Set IMAGE_TAG env
        run: echo "IMAGE_TAG=${ELASTIC_VER}-${SUDACHI_PLUGIN_VER}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        id: buildx
      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: s9-sukyu
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            ELASTIC_VER=${{ env.ELASTIC_VER }}
            SUDACHI_PLUGIN_VER=${{ env.SUDACHI_PLUGIN_VER }}
          tags: |
            ghcr.io/s9-sukyu/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

